
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.codegen.video;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeVideoDecoderInfoModuleSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "VideoDecoderInfoModule";

  public NativeVideoDecoderInfoModuleSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void getWidevineLevel(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void isCodecSupported(String mimeType, double width, double height, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void isHEVCSupported(Promise promise);
}
